version: "3"
services:
  nginx: # 服务名称
    image: nginx:latest
    ports:
      - 88:80
    volumes:
      - /home/wangyanqing/data/hillynginx/html:/usr/share/nginx/html
      - /home/wangyanqing/data/hillynginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  hillymongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: newpassword
    ports:
      - 27017:27017
    # 数据持久化
    volumes:
      - /home/wangyanqing/data/hillymongodb2:/data/db
  hillymysql:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - /home/wangyanqing/data/hillymysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: newpassword
#      MYSQL_DATABASE: hilly
#      MYSQL_USER: hilly
#      MYSQL_PASSWORD: newpassword
  hillyrabbitmq:
    image: rabbitmq:management
    container_name: hillyrabbit
    restart: always
    hostname: myRabbitmq
    ports:
      - 15675:15672
      - 5675:5672
    volumes:
      - /home/wangyanqing/data/hillyrabbitmq2/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=newpassword
  hillyproject:
    image: hilly:latest
    build: .
    ports:
      - 8088:8088
    depends_on: # 依赖与mysql、redis，其实可以不填，默认已经表示可以
      - hillymongo
      - hillyrabbitmq
      - hillymysql