version: "3"
services:
  nginx: # 服务名称
    image: nginx:latest
    ports:
      - 88:80
    volumes:
      - /home/wangyanqing/data/hillynginx/html:/usr/share/nginx/html
      - /home/wangyanqing/data/hillynginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  hillymongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: newpassword
    ports:
      - 27017:27017
    # 数据持久化
    volumes:
      - /home/wangyanqing/data/hillymongodb:/data/db
  hillyrabbitmq:
    image: rabbitmq:management
    container_name: hillyrabbit
    restart: always
    hostname: myRabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - /home/wangyanqing/data/hillyrabbitmq/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=newpassword
  hillyproject:
    image: hilly:latest
    build: .
    ports:
      - 8088:8088
    depends_on: # 依赖与mysql、redis，其实可以不填，默认已经表示可以
      - hillymongo
      - hillyrabbitmq